name: Sync

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    outputs:
      changes: ${{ steps.changes.outputs.changes }}

    strategy:
      matrix:
        repo: [
          'supportpal/addon-language-danish',
          'supportpal/addon-language-dutch',
          'supportpal/addon-language-french',
          'supportpal/addon-language-german',
          'supportpal/addon-language-persian',
          'supportpal/addon-language-portuguese',
          'supportpal/addon-language-portuguese-brazilian',
          'supportpal/addon-language-russian',
          'supportpal/addon-language-spanish',
          'supportpal/addon-language-swedish',
          'supportpal/addon-language-turkish'
        ]
        path: ['614ed54b-7b88-4936-a3a2-e1a84669010a']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout repository we want to synchronise
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repo }}
          path: ${{ matrix.path }}
          ref: master
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2, supportpal/language-tools

      - name: Set environment
        run: |
          LANG_PATH="$(find ${{ matrix.path }}/Lang -mindepth 1 -maxdepth 1 -type d -print -quit)"
          echo "LANG_PATH=$(echo $LANG_PATH)" >> $GITHUB_ENV
          echo "LANG_NAME=$(basename $LANG_PATH)" >> $GITHUB_ENV 

      - name: Sync files
        run: |
          mkdir -p ${{ matrix.path }}/.github/workflows/
          cp .github/dependabot.yml ${{ matrix.path }}/.github/
          cp .github/workflows/release.yml ${{ matrix.path }}/.github/workflows/
          cp .github/workflows/test.yml ${{ matrix.path }}/.github/workflows/
          language-tools sync Lang/en ${{ env.LANG_PATH }}

      # This step will evaluate the repo status and report the change
      - name: Check if there are changes
        id: changes
        working-directory: ${{ matrix.path }}
        run: |
          git add -A Lang/${{ env.LANG_NAME }} .github/dependabot.yml .github/workflows/release.yml .github/workflows/test.yml
          git status
          if git status | grep -q "Changes to be committed"
          then
            echo "::set-output name=changes::1"  
          else
            echo "::set-output name=changes::0"
          fi

      - name: Render template
        id: template
        uses: chuhlomin/render-template@v1.6
        with:
          template: .github/sync-template.md
          vars: |
            GITHUB_RUN_ID: ${{ github.run_id }}
            REPO_NAME: ${{ github.repository }}
            REPO_URL: ${{ github.repositoryUrl }}

      - name: Create pull request
        if: steps.changes.outputs.changes == '1'
        working-directory: ${{ matrix.path }}
        run: |
          BRANCH="sync"
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git checkout -b $BRANCH
          git commit -m "🔄 Sync https://github.com/${{ github.repository }}"
          git push --set-upstream origin $BRANCH --force
          if [ -z "$(gh pr list -S "head:$BRANCH")" ]; then
            gh pr create --base master --title "🔄 Sync ${{ github.repository }}" --body "${{ steps.template.outputs.result }}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
